server:
  port: 18088
spring:
  application:
    name: nacos-nginx-prod-auth
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #??????
        #server-addr: 192.168.126.133:8848
        server-addr: 127.0.0.1:8848
      config:
        #??????
        #server-addr: 192.168.126.133:8848
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  main:
    allow-bean-definition-overriding: true