server:
  port: 18082

spring:
  application:
    name: nacos-nginx-prod-1
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #服务注册地址
        #server-addr: 192.168.126.133:8848
        server-addr: 127.0.0.1:8848
      config:
        #配合中心地址
        #server-addr: 192.168.126.133:8848
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  main:
    allow-bean-definition-overriding: true